# -*- coding: utf-8 -*-
"""Astronaut_Image_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O7HbsTVKpM-letQMpc0DNeQbEUqpSf3i
"""

pip install torch torchvision   matplotlib pillow

import numpy as np
import matplotlib.pyplot as plt
from skimage import data, color, transform

img_raw = data.astronaut()
img_raw = transform.resize(img_raw, (200, 200))

plt.figure(figsize=(6,6))
plt.imshow(img_raw, cmap='gray')
plt.title("Original Image Of A Astronaut")
plt.axis("off")
plt.show()

kernel = np.array([
    [-1,0,1],
    [-1,0,2],
    [-1,0,1]
])

from scipy.signal import convolve2d


img_gray = color.rgb2gray(img_raw)
feature_map = convolve2d(img_gray, kernel, mode='same')

plt.imshow(np.absolute(feature_map), cmap='viridis')
plt.colorbar()
plt.show()

import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from skimage import  data, transform
import numpy as np
import matplotlib.pyplot as plt

model = VGG16(weights='imagenet', include_top = False )

img_raw_data = data.astronaut()
astro_resized = transform.resize(img_raw_data, (224,224))
x = np.expand_dims(astro_resized*255, axis=0)
x = preprocess_input(x)

mid_layer_model = tf.keras.Model(inputs=model.input, outputs=model.get_layer('block3_conv1').output)
mid_features = mid_layer_model.predict(x)

fig, ax = plt.subplots(1,2, figsize=(12,16))
ax[0].imshow(mid_features[0,:,:,10], cmap='viridis')
ax[0].set_title("Neuron 10: Text/Detail Detector")
ax[1].imshow(mid_features[0,:,:,15], cmap = 'viridis')
ax[1].set_title("Neuron 15: Edge/Shape Detector")
plt.show()

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 2, figsize=(16, 8))

ax[0].imshow(deep_features[0, :, :, 1], cmap='magma')
ax[0].set_title("Deep-layer Neuron 1 (Specialist Neuron)")
ax[0].axis('off')

ax[1].imshow(deep_features[0, :, :, 9], cmap='magma')
ax[1].set_title("Deep-layer Neuron 9 (Specialist Neuron)")
ax[1].axis('off')

plt.tight_layout()
plt.show()

"""# Learnings from the Image and Model Evaluation

1)The neuron activations are highly localized, indicating strong spatial specialization.

2)The feature maps show concentrated high-intensity regions instead of scattered noise.

3)Background regions are mostly dark, meaning the neuron suppresses irrelevant information.

4)Each neuron appears to focus on specific object parts rather than the entire image.

5)The activation blobs are sharp and well-defined, showing confident feature detection.

6)There is low activation overlap, suggesting good feature separation.

7)The model has learned meaningful hierarchical representations.

8)The neuron responses are sparse, which usually indicates efficient learning.

9)The filters appear discriminative rather than random.

10)Overall, the visualization suggests that the model has converged properly and learned structured patterns.
"""