# -*- coding: utf-8 -*-
"""CNN_Image_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvbtFWlUB3XovJZasDS3bUC9phMywG5t
"""

pip install torch torchvision matplotlib pillow

import numpy as np
import matplotlib.pyplot as plt
from skimage import data, color, transform

img_raw = data.camera()
img_raw = transform.resize(img_raw,(220,220))

plt.figure(figsize=(7,7))
plt.imshow(img_raw, cmap = 'gray')
plt.title('guy shhoting a film in his camera')
plt.axis('off')
plt.show()

kernel = np.array([
    [-1,0,1],
    [-1,0,2],
    [-1,0,1]
])

from scipy.signal import convolve2d


img_gray = img_raw
feature_map = convolve2d(img_gray, kernel, mode='same')

plt.imshow(np.absolute(feature_map), cmap='viridis')
plt.colorbar()
plt.show()

import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from skimage import  data, transform, color
import numpy as np
import matplotlib.pyplot as plt

model = VGG16(weights='imagenet', include_top = False )

img_raw_data = data.camera()
cam_resized = transform.resize(img_raw_data, (116,116))


cam_resized_rgb = color.gray2rgb(cam_resized)

x= np.expand_dims(cam_resized_rgb*255, axis=0)
x = preprocess_input(x)

mid_layer_model = tf.keras.Model(inputs=model.input, outputs=model.get_layer('block3_conv1').output)
mid_features = mid_layer_model.predict(x)

fig, ax = plt.subplots(1,2, figsize=(12,16))
ax[0].imshow(mid_features[0,:,:,10], cmap='viridis')
ax[0].set_title("Neuron 10: Text/Detail Detector")
ax[1].imshow(mid_features[0,:,:,15], cmap = 'viridis')
ax[1].set_title("Neuron 15: Edge/Shape Detector")
plt.show()

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 2, figsize=(16, 8))

ax[0].imshow(mid_features[0, :, :, 1], cmap='magma')
ax[0].set_title("Deep-layer Neuron 1 (Specialist Neuron)")
ax[0].axis('off')

ax[1].imshow(mid_features[0, :, :, 11], cmap='magma')
ax[1].set_title("Deep-layer Neuron 11 (Specialist Neuron)")
ax[1].axis('off')

plt.tight_layout()
plt.show()

"""# Learnings from the Image and Model Evaluation

1)The activations are more scattered across the image instead of being localized.

2)There is noticeable background activation, indicating weaker suppression of irrelevant features.

3)The feature maps lack sharp, concentrated activation regions.

4)The neuron specialization appears less distinct compared to the first model.

5)Activations look more diffused rather than focused.

6)There is higher noise in the representation.

7)The model may not have fully converged during training.

8)The filters seem less discriminative and more generalized.

9)Some patterns are partially detected but not strongly emphasized.

10)Overall, the visualization suggests unstable or incomplete feature learning.
"""